// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0YNT0Mve9n3Aj8BFRoQH_rVBkpiWAT1o',
    appId: '1:162237682780:web:3375e6e73d404591b50299',
    messagingSenderId: '162237682780',
    projectId: 'notesapp-28b99',
    authDomain: 'notesapp-28b99.firebaseapp.com',
    storageBucket: 'notesapp-28b99.appspot.com',
    measurementId: 'G-DXFY41SZJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqk8GQBD-sr-R-s_ZY14QyqBQRF0wtNR0',
    appId: '1:162237682780:android:78e82259a63f0020b50299',
    messagingSenderId: '162237682780',
    projectId: 'notesapp-28b99',
    storageBucket: 'notesapp-28b99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-_AEX5svtz12aCqzJjfCO4kvjAbDY7o',
    appId: '1:162237682780:ios:83336f76498804e6b50299',
    messagingSenderId: '162237682780',
    projectId: 'notesapp-28b99',
    storageBucket: 'notesapp-28b99.appspot.com',
    iosClientId: '162237682780-qdpmh0v2k6heej7eboebo3jir6t2ltg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-_AEX5svtz12aCqzJjfCO4kvjAbDY7o',
    appId: '1:162237682780:ios:83336f76498804e6b50299',
    messagingSenderId: '162237682780',
    projectId: 'notesapp-28b99',
    storageBucket: 'notesapp-28b99.appspot.com',
    iosClientId: '162237682780-qdpmh0v2k6heej7eboebo3jir6t2ltg6.apps.googleusercontent.com',
    iosBundleId: 'com.example.notesApp',
  );
}
